# Generated by Django 5.2.7 on 2025-10-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField(default=2025)),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
                ('editorial', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField(default=2025)),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
                ('editorial', models.CharField(max_length=255)),
                ('volumen', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField(default=2025)),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
                ('editorial', models.CharField(max_length=255)),
                ('volumen', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
