# Generated by Django 5.2.7 on 2025-10-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_libro_manga_novela'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('manga', 'Manga'), ('novela', 'Novela')], max_length=50)),
                ('id_referencia', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='anio_publicacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='anio_publicacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='novela',
            name='anio_publicacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='RegistroLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_actual', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('LEIDO', 'Leido'), ('PENDIENTE', 'Pendiente'), ('FAVORITO', 'Favorito'), ('ABANDONADO', 'Abandonado')], default='PENDIENTE', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.materialgeneral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'material')},
            },
        ),
    ]
