# Generated by Django 5.2.7 on 2025-10-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_materialgeneral_alter_libro_anio_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5),
        ),
    ]
