# Generated by Django 5.2.7 on 2025-10-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrolectura',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registrolectura',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
