# Generated by Django 5.2.7 on 2025-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_registrolectura_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrolectura',
            name='pagina_actual',
        ),
        migrations.RemoveField(
            model_name='registrolectura',
            name='user',
        ),
        migrations.AddField(
            model_name='registrolectura',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
