# Generated by Django 5.2.7 on 2025-10-21 20:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
                ('editorial', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
                ('editorial', models.CharField(max_length=255)),
                ('volumen', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('manga', 'Manga'), ('novela', 'Novela')], max_length=50)),
                ('id_referencia', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
                ('editorial', models.CharField(max_length=255)),
                ('volumen', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_actual', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('LEIDO', 'Leido'), ('PENDIENTE', 'Pendiente'), ('FAVORITO', 'Favorito'), ('ABANDONADO', 'Abandonado')], default='PENDIENTE', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialgeneral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'material')},
            },
        ),
    ]
