# Generated by Django 5.2.7 on 2026-01-09 13:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='perfiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro'), ('MANGA', 'Manga'), ('NOVELA', 'Novela')], max_length=10)),
            ],
            options={
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('numero_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/libros/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido_pdf', models.FileField(blank=True, null=True, upload_to='contenidos/libros/')),
                ('generos', models.ManyToManyField(blank=True, related_name='libros', to='api.generotag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=255)),
                ('tomo', models.PositiveIntegerField(default=1)),
                ('capitulos', models.PositiveIntegerField(blank=True, null=True)),
                ('estado_publicacion', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('HIATUS', 'Hiatus')], default='EN_CURSO', max_length=20)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/mangas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido_pdf', models.FileField(blank=True, null=True, upload_to='contenidos/mangas/')),
                ('generos', models.ManyToManyField(blank=True, related_name='mangas', to='api.generotag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=255)),
                ('volumen', models.PositiveIntegerField(default=1)),
                ('numero_capitulos', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('LIGERA', 'Ligera'), ('WEB', 'Web'), ('VISUAL', 'Visual')], default='LIGERA', max_length=20)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/novelas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido_pdf', models.FileField(blank=True, null=True, upload_to='contenidos/novelas/')),
                ('generos', models.ManyToManyField(blank=True, related_name='novelas', to='api.generotag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('manga', 'Manga'), ('novela', 'Novela')], max_length=50)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('novela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.novela')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manga')),
                ('novela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.novela')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('pagina_actual', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('LEIDO', 'Leido'), ('PENDIENTE', 'Pendiente'), ('FAVORITO', 'Favorito'), ('ABANDONADO', 'Abandonado')], default='PENDIENTE', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialgeneral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuarios', to='api.libro')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuarios', to='api.manga')),
                ('novela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_usuarios', to='api.novela')),
            ],
            options={
                'unique_together': {('user', 'libro'), ('user', 'manga'), ('user', 'novela')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], help_text='Calificación de 1 a 5 estrellas')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.libro')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.manga')),
                ('novela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.novela')),
            ],
            options={
                'unique_together': {('user', 'libro'), ('user', 'manga'), ('user', 'novela')},
            },
        ),
    ]
