# Generated by Django 5.2.7 on 2025-10-30 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registrolectura_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialgeneral',
            name='id_referencia',
        ),
        migrations.RemoveField(
            model_name='materialgeneral',
            name='titulo',
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.libro'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manga'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='novela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.novela'),
        ),
        migrations.AddField(
            model_name='materialgeneral',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialgeneral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
