# Generated by Django 5.2.7 on 2025-11-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_materialgeneral_id_referencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='volumen',
            new_name='tomo',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='material',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.libro'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manga'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='novela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.novela'),
        ),
    ]
